# Generated by Django 5.1.7 on 2025-03-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.TextField(default='test'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_the_box',
            field=models.TextField(default='test'),
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.TextField(default='test'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='test'),
        ),
    ]
