# Generated by Django 5.1.7 on 2025-04-08 19:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_product_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.product_image_upload_to),
        ),
    ]
